---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - multicluster-observabilities-clusterrole-and-binding.yaml
  - nfd-clusterrole-and-binding.yaml
  - nvidia-clusterrole-and-binding.yaml
  - opendatahub-clusterrole-and-binding.yaml
  - serviceaccount-redhat-ods-operator-clusterrole-and-binding.yaml
  - prometheusrules.clusterrole-and-rolebinding.yaml
